export const surveyQuestions = [
  [
    "multi",
    true,
    "Was the restaurant’s outside appearance attractive? Nice curb appeal?",
    ["Strongly Agree", "Agree", "Disagree", "Strongly Disagree", "Other"],
  ],
  ["text", true, "What was your server's name?"],
  [
    "multi",
    true,
    "Was outside appearance clean-clean windows, porch, doors, etc.?",
    ["Yes", "No"],
  ],
  ["multi", true, "Was the restaurant clean inside?", ["Yes", "No"]],
  [
    "multi",
    true,
    "Was the hostess area clean and organized?",
    [
      "5 - Very clean and well organized",
      "4",
      "3",
      "2",
      "1 - Not at all clean or organized",
    ],
  ],
  [
    "multi",
    true,
    "Were the bathrooms well stocked and cleaned?",
    ["Yes", "No"],
  ],
  [
    "multi",
    true,
    "Were you promptly greeted by the host/hostess?",
    ["Yes", "No"],
  ],
  [
    "multi",
    false,
    "If the host/hostess was occupied, did they say that they would be right with you?",
    ["Yes", "No"],
  ],
  [
    "multi",
    true,
    "Was the server knowledgeable about the menu?",
    ["Yes", "No"],
  ],
  [
    "multi",
    true,
    "Did the server suggest a beverage or appetizer?",
    ["Yes", "No"],
  ],
  [
    "multi",
    true,
    "Was the server's appearance appropriate to the nature of the restaurant?",
    ["Yes", "No"],
  ],
  ["multi", true, "Did the food arrive in a timely fashion?", ["Yes", "No"]],
  [
    "multi",
    true,
    "Did the server check back with you during the course of your meal?",
    ["Yes", "No"],
  ],
  [
    "multi",
    true,
    "Were the plates cleared at the end of your meal?",
    [
      "Agree",
      "Somewhat Agree",
      "Neutral",
      "Somewhat Disagree",
      "Strongly Disagree",
    ],
  ],
  [
    "multi",
    true,
    "What was your overall experience with the customer service?",
    ["5 - Excellent ", "4", "3", "2", "1 - Poor"],
  ],
  [
    "multi",
    true,
    "How would you rate the overall presentation and taste of the food?",
    ["5 - Excellent ", "4", "3", "2", "1 - Poor"],
  ],
  [
    "multi",
    true,
    "How would you rate the quality of the food you received?",
    ["5 - Excellent ", "4", "3", "2", "1 - Poor"],
  ],
  [
    "multi",
    true,
    "Did a manager or other team member check on your table during your stay?",
    ["Yes", "No"],
  ],
];
